version: '2'
services: 
  registry:
    image: registry:2
    environment:
      REGISTRY_AUTH: 'htpasswd'
      REGISTRY_AUTH_HTPASSWD_REALM: 'Docker Registry'
      REGISTRY_AUTH_HTPASSWD_PATH: '/auth/htpasswd'
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'
    ports:
      - 5000:5000
      - 80:5000
    volumes:
      - /auth:/auth
