apiVersion: v1
kind: Service
metadata:
  name: drone
spec:
  type: NodePort
  ports:
    - name: drone-http-svc
      protocol: TCP
      port: 80
      targetPort: drone-http
      nodePort: 30080
    - name: drone-rpc-svc
      protocol: TCP
      port: 9000
      targetPort: drone-rpc
      nodePort: 30900
  selector:
    app: drone

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone
  labels:
    app: drone
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: drone
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: drone
    spec:
      containers:
        - name: drone
          image: drone/drone:2.12
          env:
            - name: DRONE_HTTP_SSL_HOST
              value: {{TRAFFIC_HOST1_30080}}
              #value: 9a8906c3-49b2-4ae1-917a-9f476ef2d0a9-10-244-5-254-30080.saci.r.killercoda.com
            - name: DRONE_RPC_SECRET
              # $ openssl rand -hex 16
              value: 96cc18d386b514b225f6396605aa44a4
            - name: DRONE_SERVER_HOST
              value: {{TRAFFIC_HOST1_30080}}
              #value: 9a8906c3-49b2-4ae1-917a-9f476ef2d0a9-10-244-5-254-30080.saci.r.killercoda.com
            - name: DRONE_SERVER_PROTO
              value: https
            - name: DRONE_GITEA_SERVER
              value: https://{{TRAFFIC_HOST1_30000}}
              #value: https://9a8906c3-49b2-4ae1-917a-9f476ef2d0a9-10-244-5-254-30000.saci.r.killercoda.com
            - name: DRONE_GITEA_CLIENT_ID
              value: 2f1940bd-0aff-4546-b13d-c34eafad1d32
            - name: DRONE_GITEA_CLIENT_SECRET
              value: n1ZffRu090F1r5rkd9wRzdry0zF8b3Z76ppT997OZ8mm
          livenessProbe:
            httpGet:
              path: /
              port: drone-http
          ports:
            - name: drone-http
              containerPort: 80
            - name: drone-rpc
              containerPort: 9000