apiVersion: v1
kind: Service
metadata:
  name: gitea
spec:
  ports:
    - name: gitea-http-svc
      protocol: TCP
      port: 8080
      targetPort: gitea-http
    - name: gitea-https-svc
      protocol: TCP
      port: 8443
      targetPort: gitea-https
  selector:
    app: gitea

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  labels:
    app: gitea
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: gitea
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
        - name: gitea
          image: gitea/gitea:1.16.8
          livenessProbe:
            httpGet:
              path: /
              port: gitea-http
          ports:
            - name: gitea-http
              containerPort: 80
            - name: gitea-https
              containerPort: 443