apiVersion: v1
kind: Service
metadata:
  name: gitea
spec:
  type: NodePort
  ports:
    - name: gitea-ssh-svc
      protocol: TCP
      port: 3022
      targetPort: gitea-ssh
      nodePort: 30022
    - name: gitea-http-svc
      protocol: TCP
      port: 8080
      targetPort: gitea-http
      nodePort: 30000
  selector:
    app: gitea

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  labels:
    app: gitea
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: gitea
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
        - name: gitea
          image: gitea/gitea:1.16.8
          volumeMounts:
            - name: gitea-config
              mountPath: /data/gitea/conf
          livenessProbe:
            httpGet:
              path: /
              port: gitea-http
          ports:
            - name: gitea-ssh
              containerPort: 22
            - name: gitea-http
              containerPort: 3000
      volumes:
        - name: gitea-config
          configMap:
            name: gitea-config