---
kind: pipeline
type: docker
name: example

steps:
  - name: myEnvironment
    image: alpine:3.10
    when:
      status:
        - success
        - failure
    environment:
      SOMETHING_JUICY: oranges
      SOMETHING_UNIQ: 1
      SOMETHING_PRIVATE:
        from_secret: something_private
    commands:
      - apk add --no-cache tree
      - touch SOMETHING_STICKY.txt
      - echo "glue" >> SOMETHING_STICKY.txt
      - |
        echo ------------------------------------------------------------
        echo "Environment Variables"
        echo ------------------------------------------------------------
        env | sort -n
        echo ------------------------------------------------------------
        echo "Working Directory '$(pwd)'"
        echo ------------------------------------------------------------
        tree -R .
        echo ------------------------------------------------------------
        echo "Print File (Outside HereDoc)"
        echo ------------------------------------------------------------
      - cat $DRONE_WORKSPACE/SOMETHING_STICKY.txt

trigger:
  branch:
    - master
...
