version: '3.2'

services:
  elasticsearch:
    image: elasticsearch:5.3.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      DISCOVERY_TYPE: single-node

  heartbeat:
    image: docker.elastic.co/beats/heartbeat:5.3.1
    volumes:
      - './heartbeat.yml:/usr/share/heartbeat/heartbeat.yml:ro'
    depends_on:
      - elasticsearch
